baseurl: ""
blackfriday:
  fractions: false
disableKinds: ["taxonomy", "taxonomyTerm", "sitemap"]
footnotereturnlinkcontents: "↩"
frontmatter:
  date: [":filename", ":default"]
ignoreFiles: ["\\.rds$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
params:
  author: Vincent M. Nolette
  email: vincent.nolette@motu.org.nz
  facebook: https://www.facebook.com/vincent.nolette
  github: https://github.com/vincentnolette
title: vmnolette
